### ISSUE TITLE
Polyfill Object.assign for legacy node

### ISSUE THREAD

**Issue by r1b** [inquisive/expression-match#6]
See https://github.com/keystonejs/keystone/issues/2151

```
rcj@mcdouble:keystone $ node --version
v0.12.9
rcj@mcdouble:keystone $ npm test
<snip>
  1) Test dependsOn and required Ignore required if evalDependsOn is not `true` by setting `state` to `draft`:
     Uncaught TypeError: undefined is not a function
      at new ExMatch (node_modules/expression-match/ExMatch.js:68:26)
      at new module.exports (node_modules/expression-match/ExMatch.js:24:9)
      at evalDependsOn (fields/utils/evalDependsOn.js:12:14)
      at model.Field.options.required (fields/types/Type.js:73:41)
      at model.requiredValidator (node_modules/mongoose/lib/schematype.js:531:59)
      at node_modules/mongoose/lib/schematype.js:709:28
      at Array.forEach (native)
      at SchemaDate.SchemaType.doValidate (node_modules/mongoose/lib/schematype.js:683:19)
      at node_modules/mongoose/lib/document.js:1194:9

  2) Test dependsOn and required Save will fail if `state` set to `published` and `publishedDate` is not defined:
     Uncaught TypeError: undefined is not a function
      at new ExMatch (node_modules/expression-match/ExMatch.js:68:26)
      at new module.exports (node_modules/expression-match/ExMatch.js:24:9)
      at evalDependsOn (fields/utils/evalDependsOn.js:12:14)
      at model.Field.options.required (fields/types/Type.js:73:41)
      at model.requiredValidator (node_modules/mongoose/lib/schematype.js:531:59)
      at node_modules/mongoose/lib/schematype.js:709:28
      at Array.forEach (native)
      at SchemaDate.SchemaType.doValidate (node_modules/mongoose/lib/schematype.js:683:19)
      at node_modules/mongoose/lib/document.js:1194:9

  3) Test dependsOn and required Save will succeed if `state` set to `published` and `publishedDate` is defined:
     Uncaught TypeError: undefined is not a function
      at new ExMatch (node_modules/expression-match/ExMatch.js:68:26)
      at new module.exports (node_modules/expression-match/ExMatch.js:24:9)
      at evalDependsOn (fields/utils/evalDependsOn.js:12:14)
      at model.Field.options.required (fields/types/Type.js:73:41)
      at model.requiredValidator (node_modules/mongoose/lib/schematype.js:531:59)
      at node_modules/mongoose/lib/schematype.js:709:28
      at Array.forEach (native)
      at SchemaDate.SchemaType.doValidate (node_modules/mongoose/lib/schematype.js:683:19)
      at node_modules/mongoose/lib/document.js:1194:9
```

**Comment by snowkeeper** [comment]
Thanks @erg0dic !.  Pushed an update...
